pr: none
trigger:
- master
variables:
- group: exoplanet-variables
pool:
  vmImage: Ubuntu-16.04

steps:
- script: |
    source .ci/azure/setup_conda.sh
  displayName: 'Setup conda'

- script: |
    source .ci/azure/activate_conda.sh
    env/bin/python -m pip install -U -r paper/requirements.txt
    conda install -y -q -c conda-forge tectonic
  displayName: 'Install dependencies'

- script: |
    source .ci/azure/activate_conda.sh
    cd $(Build.SourcesDirectory)/paper/figures
    python run_notebooks.py
  displayName: 'Generate the figures'

- script: |
    source .ci/azure/activate_conda.sh
    cd $(Build.SourcesDirectory)/paper
    make
  displayName: 'Build the paper'

- script: |
    cd $(Build.SourcesDirectory)
    git checkout --orphan $(Build.SourceBranchName)-pdf
    git rm -rf --cached .
    git add -f paper/exoplanet.pdf
    git add -f paper/figures/*.pdf
    git add -f paper/figures/*_exec.ipynb
    git add -f paper/figures/notebook_errors.log
    git -c user.name='azure' -c user.email='azure' commit -m "building the paper"
    git push -q -f https://$(GITHUB_USER):$(GITHUB_API_KEY)@github.com/exoplanet-dev/exoplanet $(Build.SourceBranchName)-pdf >/dev/null 2>&1
  displayName: 'Upload the paper'
  condition: always()
